doc/manual/source/parameters/index.rst

@kohdaegene pointed out that the parameters for magnetic supernova feedback were missing from the parameters documentation page.

Adding MagneticSupernova parameter documentation

---

src/enzo/New_Grid_ReadGrid.C

This is described by the discussion in Issue #79 , and implements the fix described there.  It fixes a bug where the recently-accepted active particle PR (PR #57 ) breaks restarts from simulations that have particles but predate the active particle PR merge (which is to say, almost all Enzo simulations ever).

Small tweak to hierarchy file reader - patch for pre-AP simulations

---

src/enzo/ReadParameterFile.C

This is a quick fix to make Enzo to be fully functional with all of Grackle’s features.  (Previously these four Enzo parameters were not mapped to their respective Grackle parameters.)  This fix -- identified by myself (Ji-hoon) and Britton -- will also make Enzo to be fully compatible with other codes in the AGORA comparison test suites of cosmological runs.  
(FYI, the only other place where RadiationRedshift* parameters are used is in Enzo is RadiationFieldCalculateRates.C.  This file is not used anyway if RadiationFieldType = 0 -- which is often the case when Grackle is employed for cooling/radiation calculations.)

Fixes to map RadiationRedshift* parameters to Grackle

---

src/enzo/Grid.h
src/enzo/hydro_rk/Grid_Hydro3D.C
src/enzo/hydro_rk/Grid_MHD3D.C
src/enzo/hydro_rk/Grid_MHDRK2_1stStep.C
src/enzo/hydro_rk/Grid_MHDRK2_2ndStep.C
src/enzo/hydro_rk/Grid_MHDSourceTerms.C
src/enzo/hydro_rk/Grid_RungeKutta2_1stStep.C
src/enzo/hydro_rk/Grid_RungeKutta2_2ndStep.C
src/enzo/hydro_rk/Grid_SourceTerms.C
src/enzo/hydro_rk/HydroSweepX.C
src/enzo/hydro_rk/HydroSweepY.C
src/enzo/hydro_rk/HydroSweepZ.C
src/enzo/hydro_rk/MHDSweepX.C
src/enzo/hydro_rk/MHDSweepY.C
src/enzo/hydro_rk/MHDSweepZ.C

The implementation of the MinimumPressureSupportParameter in HydroMethod = 3 and 4 was inconsistent between the two HydroMethods, had hard-coded parameters, and didn't match the implementation in the Zeus solver. When I ran a cosmological simulation with MinimumPressureSupport and the hydro solvers, I got some pretty unphysical values in the temperature and gas energy.  This fix keeps the original framework of the MinimumPressureSupport implementation found in the hydro_rk/ files, but calculates the "min_coeff" parameter with Grid_SetMinimumSupport for consistency.

Fixing MinimumPressureSupport in hydro_rk solvers

---

.circleci/config.yml

This should confirm whether the test failures are being caused by the changes to Grackle. This change will cause the gold standard to be regenerated using the latest Grackle, but will still use the same Enzo gold standard changeset.

Change test answers cache name, but do not change gold standard.

---

.circleci/config.yml
configure

I'm open to this being rejected outright, but I thought since our make system uses bash we might as well be consistent with that. Also, fewer people use csh anymore and so you frequently have to install it.

Switch configure script to bash.

---

.circleci/config.yml
src/enzo/ActiveParticle_RadiationParticle.C
src/enzo/ConvertParticles2ActiveParticles.C
src/enzo/Grid.h
src/enzo/Grid_DebugCheck.C
src/enzo/Make.config.targets
src/enzo/Make.mach.linux-gnu
src/enzo/ParticleAttributeHandler.h
src/enzo/PhotonPackage.h
src/enzo/ReadStarParticleData.C
src/enzo/WriteHDF5HierarchyFile.C

I added a couple nested loops to test different combos of baryon/particle precision and integers/particle id precision. So to not do too many, I skip the combinations where the precision is the same. There is also a check to see if Enzo compiles without mpi.

Add test of various compile options.

---

method-paper-joss-2019/LICENSE
method-paper-joss-2019/README.md
method-paper-joss-2019/paper.bib
method-paper-joss-2019/paper.md

This PR moves the new (2019) Enzo method paper from its own repository into the main enzo repository, as required by the JOSS guidelines.

Added JOSS paper to enzo-dev repository

---

doc/manual/source/index.rst
doc/manual/source/physics/adaptive_mesh.rst
doc/manual/source/physics/gravity.rst
doc/manual/source/physics/hydro_methods.rst
doc/manual/source/physics/index.rst
doc/manual/source/reference/EnzoPrimaryReferences.rst
doc/manual/source/user_guide/index.rst

This PR addresses issues #95, #100, and #107 , as pointed out by @zingale.  Specifically, it:
- Updates sections of the user guide introduction to reflect the 2014 Enzo method paper and number of Enzo parameters (Issue #95 )
- Adds a new section to the documentation to describe the AMR algorithm in more detail (Issue #100)
- Clarifies capabilities/limitations in the fluid solvers and gravity solver (Issue #107 )

[JOSS] Addressing several physics, AMR, and citation issues in Enzo docs

---

.circleci/config.yml
README.md
src/enzo/Make.mach.linux-gnu
src/enzo/Make.mach.ubuntu

Addresses #96 
Adds info on requirements already at the README level and make the instructions for GNU/Linux more generic.
I also renamed `README` to `README.md` and updated the content to use markdown so that it's properly rendered on GitHub.

[JOSS] Requirements

---

doc/manual/source/reference/EnzoInternalUnits.rst

This addresses issue #103, clarifies use gravitational units in documentation.

[JOSS] Clarified choice of gravitational units in documentation

---

doc/manual/source/index.rst

The FAQ chapter appears to be duplicated in the docs.  Once near the middle and again at the end.  
https://enzo.readthedocs.io/en/enzo-2.6/index.html
This removes the latter.

remove duplicate FAQ entry

---

.circleci/config.yml

This updates the gold standard to a version after the testing make file name was changed.
Note, this will fail until we push the `gold-standard-v13` tag to the main repo after merging this.

Update gold standard.

---

src/enzo/OutputFromEvolveLevel.C

Simple PR. Not sure if this is a bugfix or if this check was intentionally left out of `OutputFromEvolveLevel`, but I feel including this check here makes sense (as I found out the hard way when I filled up my hard drive....).

Bugfix: NumberOfOutputsBeforeExit for sub-cycle outputs

---

src/enzo/GrackleReadParameters.C
src/enzo/Make.config.objects
src/enzo/ReadParameterFile.C
src/enzo/SetDefaultGlobalValues.C
src/enzo/WriteParameterFile.C
src/enzo/pop3_maker.F
src/enzo/typedefs.h

Fixes bugfix in mapping Grackle's default parameters to the equivalent Enzo parameters when Grackle is compiled but not in use. This now only occurs when Grackle is actually in use.
I threw this together quickly and just tested that this fixes the crashes that happened in  PhotonTestAMR. So worth a look.
(This PR includes a couple very minor (but fully unrelated) commits from another currently open but accepted PR)

Bugfix running with Grackle compiled but Grackle off

---

doc/manual/source/parameters/index.rst
src/enzo/Grid_AddH2Dissociation.C
src/enzo/RadiativeTransferParameters.h
src/enzo/RadiativeTransferReadParameters.C

Removing an ifdef in favor of a run-time parameter to turn on / off source clustering with optically thin radiation. 
A few years ago I had tested this routine and found it to give strange results, but I recently tried to use this again and it looks like it is behaving well. I'm not sure what has changed between then and now that fixed this, but none of the commit logs in the clustering routines seem to be more recent than when I first looked at this. Its possible there was some issue in an unrelated piece of code from my individual stars methods that affected this that has since been fixed, but tracking this down would be hard. 
I added a word of caution to the docs on using this piece of code just in case weird things happen again. It speeds up computation considerably (> factor of 10) …

Optically Thin Source Clustering

---

src/enzo/EvolveLevel.C

ActiveParticleFinalize function removed from the loop over grids.  Active particle counting over all grids and processors is already done 
inside CommunicationUpdateActiveParticleCount function which is getting called in ActiveParticleFinalize function. So, no need to loop over grids again.

Bugfix for ActiveParticleFinalize function call

---

.circleci/config.yml

This configures circleci to run the test suite once a week (Monday at midnight). This should make it easier to catch issues that crop up because of changes in dependencies, like Grackle.

Add weekly tests

---

src/enzo/CommunicationCollectParticles.C
src/enzo/CommunicationTransferSubgridParticles.C
src/enzo/Grid.h
src/enzo/Grid_CollectStars.C
src/enzo/Grid_CommunicationSendStars.C
src/enzo/Grid_CommunicationTransferStarsOpt.C
src/enzo/Grid_TransferSubgridStars.C
src/enzo/Star.h
src/enzo/StarParticleFindAll.C
src/enzo/StarRoutines.C
src/enzo/macros_and_parameters.h
src/enzo/pop3_maker.F
src/enzo/typedefs.h

This fixes / improves star particle communication to address memory fragmentation and performance issues when running with many (> 10k) star particle objects.
These changes are all circa 2016, but fell through the cracks in getting pulled into the main repository. Caught this when merging my fork with the active particle changes. Some of these changes parallel what is done with active particles. 
All credit goes to John Wise, stemming from the following commits: [May 2016 (1 of 2)](https://bitbucket.org/jwise77/enzo-dev/commits/ba5202af3d2c6102bd82ca644fed3c373e6552e8), [May 2016 (2 of 2)](https://bitbucket.org/jwise77/enzo-dev/commits/703f1091d58a4e12cc6720bc08ef12581e56792f), [June, 2016](https://bitbucket.org/jwise77/enzo-dev/commits/2981eb07b9effb06e490a38047fefa5bfb8237a2)

Star Particle Communication Bugfixes

---

.gitignore
doc/manual/Makefile
doc/manual/source/user_guide/RunTestProblem.rst
doc/manual/source/user_guide/SampleParameterFiles.rst
doc/manual/source/user_guide/index.rst
doc/manual/source/user_guide/samples/SG64-L2.conf
doc/manual/source/user_guide/samples/wise2014_zoomin_update.enzo

It's common for people to request/share parameter files from publications. @brittonsmith asked if I could make a shared Google doc for my simulations, and I thought it'd be best to add it to the Enzo documentation. I hope others think this is a good addition and will contribute their parameter files in the future!
The rendered html (without the theme) can be seen [here](https://www.dropbox.com/personal/temp?preview=SampleParameterFiles.html).

Adding a page with sample parameter files

---

doc/manual/source/parameters/index.rst
src/enzo/StochasticForcing_Init.C

This commit fixes two issues my collaborators and I have encountered when using the StochasticForcing problem:
1) The docs have an error for the DrivenFlowProfile parameter, in which the value for 'band' and 'parabolic window' are switched. This conflicts with correct statements in the comments of the .enzo file  run/MHD/3D/StochasticForcing/StochasticForcing.enzo and the definitions in typedefs.h from lines 201-204.
2) For certain sets of compilers, some amplitudes of the driving field are incorrectly non-zero, because they are never explicitly set in the code. Here I just add some else statements that guarantee these amplitudes are zero when they should be in the Band case.

Minor changes for StochasticForcing

---

src/enzo/ActiveParticleInitialize.C
src/enzo/DeleteRadiationSource.C
src/enzo/EvolvePhotons.C
src/enzo/StarParticleRadTransfer.C

Memory leak fix in radiation sources:
1) small fix in `EvolvePhotons`. Sources would sometimes (all of the time?) not get deleted properly in the main EvolvePhotons loop after the end of their life. Placing an additional check after the loop to see if there are any sources with lifetimes < PhotonTime. This is likely not that large of a leak since it only occurs once per radiation source (at the end of its life) and the `RadiationSourceEntry` structs aren't very large. 
2) Larger leak fix. `StarParticleRadTransfer.C` deletes and re-creates the `GlobalRadiationSources` list every call, but this was not being done correctly. Using call to `DeleteRadiationSource` properly now which properly deletes the allocated arrays in the struct.

Memory leak fix - deleting radiation sources 

---

.circleci/config.yml
doc/manual/source/conf.py
doc/manual/source/reference/NestedGridParticles.rst
doc/manual/source/supplementary_info/EmbeddedPython.rst
src/enzo/python_bridge/problemtype_handler.pyx

The latest major release of matplotlib clashes with the lastest stable yt release, which is why the tests are failing. This avoids installing the clashing matplotlib version. I also went ahead and updated to the latest version of Python for the testing.
The last commit adds names to the circleci script so that the appearance on circleci shows that name and not a smashed together string of all the commands. Unfortunately, it requires everything to go two spaces to the right, but it does make the ci easier to parse.
Apparently the docs build was also failing with a dead intersphinx link, which led me to discover a number of links to yt.enzotools.org, which I have changed to yt-project.org. Unfortunately, we also linked to a script that is no longer available, so I just left a note about …

fix ci testing

---

src/enzo/Grid_CreateParticleTypeGrouping.C

When compiling with GCC 9.3.0 and HDF 1.12.0, I got the following error
and needed to make this small change to get it to compile.
```
Grid_CreateParticleTypeGrouping.C: In member function 'long_int grid::CreateParticleTypeGrouping(hid_t, hid_t, hid_t, hid_t)':
Grid_CreateParticleTypeGrouping.C:68:35: error: cannot convert 'hdset_reg_ref_t' to 'const void*'
68 |                      H5P_DEFAULT, reference);
|                                   ^~~~~~~~~
|                                   |
|                                   hdset_reg_ref_t
```

HDF5 reference fix

---

src/enzo/Grid_GrackleWrapper.C

This changes the behavior when metal cooling has been enabled, but there is no metal field present. Previously, we disable metal cooling and keep running. I argue this is not what the user would want. Personally, I would rather the simulation not run instead of running in a way I hadn't intended, especially since the warning statement will most likely be missed. As well, there is a bug here because while `MetalCooling` is set to 0, the corresponding parameter within Grackle is not, so this results in wild behavior as Grackle tries to access `BaryonField[0]` (i.e., the gas density) as the metal density.

Exit with error if metal cooling on but no metal field present.

---

src/enzo/Make.mach.linux-gnu

`Make.mach.linux-gnu` contains a typo in `LOCAL_INCLUDES_HDF5` that causes the HDF5 header not to be found.

Fix HDF5 include path

---

src/enzo/GrackleReadParameters.C
src/enzo/hydro_rk/Grid_CollapseMHD3DInitializeGrid.C

This was causing an I/O crash because the data label was never associated with it in the problem initializer. h/t Armin M. on the mailing list for pointing this out.
I'm also including a minor fix to the MassUnits to be double instead of float. This causes compiler issues when using mixed precision.

Removing DebugField from MHD collapse problem

---

src/enzo/GrackleReadParameters.C

**Star objects:** The recent change in #120 was missing a line that first checks whether there are any local star objects before copying them to a comm buffer.
**Must-refine:** Allow for some machine-precision epsilon when comparing particle masses to determine which initial nested level they came from. Also related, the `f` suffixes in the EPSILON defines caused them to be 32-bit floats instead of 64- or 128-bit.

Bugfix: must-refine particles identification by mass

---

src/enzo/EnzoTiming.h

For some reason, the min/max functions returned bool types instead of the templated type T. After this change, performance.h now reports the correct min/max values for each performance timer.
There is only 1 effective commit in this PR with the first one (b833391) being already incorporated into another PR and the others being merges. Whoever merges this PR should rebase/squash to remove them.

Corrected min/max reporting in performance.h

---

src/enzo/global_data.h

This is designed to be a no-op change.  What it does is move all variable definitions in `global_data.h` to their own line, which makes parsing the file easier.
This is in preparation for a forthcoming PR to add support for `libyt` and move to Python 3.

Make all global_data.h declarations on their own line

---

src/enzo/Grid.h
src/enzo/PhotonPackage.h

Another extremely minor PR.  When I was dealing with a number of self-inflicted compile-time errors, I was getting lots and lots of output about the literals needing spaces in C++11.  This fixed those and made it a lot easier for me to pick out all the stuff *I* broke.

Fix C++11 compile-errors

---

doc/manual/source/parameters/index.rst
src/enzo/solve_rate_cool.F

Currently, RadiationShield = 2 selects H2 self-shielding from Wolcott-Green et al. (2011). This fit was updated in Wolcott-Green & Haiman (2019) for a wider range of density and temperatures. I have added the new self-shielding fit for RadiationShield = 3 and kept the old fit with RadiationShield = 2 for backward compatibility, but the new fit should be used by default if one wants to include H2 self-shielding.

Adding updated H2 self-shielding fit from Wolcott-Green & Haiman 2019

---

.readthedocs.yaml
doc/manual/source/conf.py

Intersphinx isn't supported in sphinx v7.0, so I'm removing it. The same was done by @mabruzzo in Enzo-E (enzo-project/enzo-e#305).

Updating intersphinx syntax and readthedocs config

---

src/enzo/Make.mach.conda

It can be convenient to install using a conda environment.  This adds a makefile that uses a conda environment for its packages.
In some specific cases, this becomes extra useful for using embedded python via libyt, which will be addressed in a forthcoming PR.

Add Make.mach.conda

---

src/enzo/Grid_NestedCosmologySimulationInitializeGrid.C

Removed the particle mass multiplier added for init ICs in Grid_NestedCosmologySimulationInitializeGrid.C that can cause errors with MUSIC ICs as described in the issue #219 .

Addressing issue #219 with incorrect particle mass

---

.circleci/config.yml
src/enzo/Make.mach.ubuntu

Update CircleCI Python several versions for future proofing

---

src/enzo/GalaxySimulationInitialize.C

Added small change to GalaxySimulation to initialize the correct particle boundary in the exterior boundary condition.

Very small GalaxySimulation fix (to initialize particle boundary type)

---

doc/manual/source/parameters/index.rst
doc/manual/source/physics/star_particles.rst
src/enzo/EvolveLevel.C
src/enzo/Grid.h
src/enzo/Grid_StarParticleHandler.C

Extended existing `StarFormationOncePerRootGridTimeStep` functionality to Normal Star (star_maker2.F). Also adjusted what grids `StarFormationOncePerRootGridTimeStep` triggers on. Previously, it only allowed star formation on grids that were at the maximum refinement level. Since each star maker routine checks that a cell is the most refined representation for its volume, this restriction is unnecessary and prevents star formation in cells where it would otherwise occur.

Added StarFormationOncePerRootGridTimeStep to Normal Star

---

input/gen_equilibrium_table.py
src/enzo/ReadEquilibriumTable.C

I committed an old, incompatible version of gen_equilibrium_table.py with nonsense units in PR #191 🙃 
This version is copied directly from https://github.com/clairekope/CGM-sim-analysis
As a reminder, this script is useful for generating a table of equilibrium chemistry values. This table is currently usable with the GalaxySimulation problem type. Now the table will save species **mass fractions** as expected by the machinery in said problem type.

Add correct, newer gen eq table script!

---

src/enzo/ExternalBoundary_SetGalaxySimulationBoundary.C

This small PR makes a few corrections to the specialized ExternalBoundary machinery that is part of the GalaxySimulation framework so that the gas coming in the boundary correctly respects the DualEnergyFormalism, HydroMethod, and Multispecies flags.

Fix GalaxySimulation boundary to work correctly with DualEnergyFormalism

---

src/enzo/Make.config.assemble

**Pull request summary**
There is a wrong indent in every option code block's last `ifeq` statement. 
Albeit the wrong indent, this never leads to an error because the last `ifeq` statement checks if the option is valid, which has already been checked in `Make.config.targets`.
**Describe your pull request**
Although the workflow will never enter this `ifeq` statement and corrupt the Makefile, it is better to fix the syntax error.
This PR fixed the wrong indent in `Make.config.assemble`.

Wrong indent in `Make.config.assemble` in ifeq statement

---

src/enzo/Grid_GrackleWrapper.C

This fixes an issue introduced in [Grackle PR #121](https://github.com/grackle-project/grackle/pull/121), where we removed a seemingly arbitrary cap on the metal density. This cap is necessary in Enzo as star formation feedback can produce grid cells where the metal density exceeds the gas density. This may not be either the best fix or the best place to put it, but this PR is as close to restoring prior functionality as is possible without putting it back into Grackle, which we don't want to do. I'm happy for this PR to be a place for a broader conversation.

Return metal density cap.

---

src/enzo/solve_rate_cool.F

---
name: Thinh Huu Nguyen
about: Fix bugs in $H_2$ self-shielding implementations
---
**Pull request summary**
Fix bugs in the Sobolev-like approximation in the $H_2$ self-shielding implementation.
**Describe your pull request**
There are two bugs in the Sobolev-like approximation formulas of the $H_2$ self-shielding implementations. The Sobolev-like approximation is activated by setting _RadiativeTransferOpticallyThinH2 == 1_ and _RadiationShield == 2_ in the parameter file. The code to implement is _[**solve_rate_cool.F**](https://github.com/enzo-project/enzo-dev/blob/main/src/enzo/solve_rate_cool.F#L1209)_. The two bugs are:
1. On Line [1209](https://github.com/enzo-project/enzo-dev/blob/main/src/enzo/solve_rate_cool.F#L1209), we compute the variable $b_5$ (or $b_{\text{Doppler}}$) to …

Fix bugs in H2 self-shielding implementations
